name: Update COVERAGE map

on:
  schedule:
    - cron: "0 17 * * *"   # runs every day at midnight Vietnam time (GMT+7)
  workflow_dispatch:       # allow manual run from GitHub
  workflow_call:           # so it can be used in other workflows

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgeos-dev proj-bin proj-data libproj-dev gdal-bin libgdal-dev
          pip install \
            earthengine-api \
            geemap \
            folium \
            branca \
            jinja2 \
            jupyter \
            geopandas \
            cartopy


      - name: Save Service Account Key
        run: |
            echo '${{ secrets.GEE_KEY }}' > key.json

      - name: Run update notebook
        run: |
          # Convert notebook to Python script (optional) and run it
          jupyter nbconvert --to python MAP03_Mangrove_COVERAGE.ipynb
          python MAP03_Mangrove_COVERAGE.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: key.json
          GEE_SERVICE_ACCOUNT: ${{ secrets.GEE_SERVICE_ACCOUNT }}


      - name: Commit and push results
        run: |
          git config user.name "Map Bot"
          git config user.email "bot@example.com"
          git add Mangrove_COVERAGE_map.html  
          git commit -m "Automated map update" || echo "No changes to commit"
          git push
